CREATE TABLE IF NOT EXISTS author(
    id SERIAL PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    bookList CHAR(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS book(
    id SERIAL PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    print_year VARCHAR(50) NOT NULL,
    author_name VARCHAR(50) NOT NULL
);